# Generated by Django 5.1.3 on 2025-05-15 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
