# Generated by Django 5.1.3 on 2025-05-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_doctors_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='nom',
            field=models.CharField(default='vide@mail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='prenom',
            field=models.CharField(default='Esther', max_length=100),
            preserve_default=False,
        ),
    ]
