# Generated by Django 5.1.3 on 2025-05-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_doctors_email_doctors_nom_doctors_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
