# Generated by Django 5.1.3 on 2025-05-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_medecin_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10, null=True),
        ),
    ]
