# Generated by Django 5.1.3 on 2025-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_remove_patient_adresse_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='etat_patient',
            field=models.CharField(choices=[('A', 'Assuré(e)'), ('N', 'Non Assuré(e)')], max_length=10),
        ),
    ]
