# Generated by Django 5.1.3 on 2025-07-30 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_alter_patient_etat_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alerte_medicale',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('diagnostic', models.TextField()),
                ('traitement', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('terminee', models.BooleanField(default=True)),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctor.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient')),
            ],
        ),
    ]
