# Generated by Django 5.1.3 on 2025-08-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0008_patient_alerte_medicale_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonctionnalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('En développement', 'En développement'), ('En test', 'En test'), ('Désactivée', 'Désactivée')], default='Disponible', max_length=20)),
            ],
        ),
    ]
