# Generated by Django 5.1.3 on 2025-08-03 01:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0009_fonctionnalite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_antecedent', models.CharField(choices=[('allergie', 'Allergie'), ('maladie_chronique', 'Maladie chronique'), ('chirurgie', 'Chirurgie'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('important', models.BooleanField(default=False, help_text='Est-ce un antécédent vital pour le traitement ?')),
                ('medecin', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents', to='Doctor.patient')),
            ],
        ),
    ]
