# Generated by Django 5.1.3 on 2025-08-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0010_antecedent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedent',
            name='type_antecedent',
            field=models.CharField(choices=[('allergie', 'Allergie'), ('maladie_chronique', 'Maladie chronique'), ('medical', 'Antécédent médical'), ('chirurgical', 'Antécédent chirurgical'), ('diagnostic', 'Diagnostic en cours'), ('critique', 'Information critique'), ('autre', 'Autre')], max_length=50),
        ),
    ]
