# Generated by Django 5.1.3 on 2025-08-03 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0011_alter_antecedent_type_antecedent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescription', models.DateTimeField(default=django.utils.timezone.now)),
                ('medicaments', models.TextField(help_text='Liste des médicaments prescrits, séparés par des virgules')),
                ('posologie', models.TextField(help_text='Indications de prise : dosage, fréquence, durée…')),
                ('remarques', models.TextField(blank=True, help_text='Commentaires supplémentaires si nécessaire', null=True)),
                ('medecin', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='Doctor.patient')),
            ],
        ),
    ]
