# Generated by Django 5.1.3 on 2025-08-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0012_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicaments',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='remarques',
        ),
        migrations.AddField(
            model_name='prescription',
            name='duree_traitement',
            field=models.PositiveIntegerField(default=7, help_text='Durée en jours'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='nom_medicament',
            field=models.CharField(default=7, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='posologie',
            field=models.TextField(),
        ),
    ]
