# Generated by Django 5.1.3 on 2025-08-03 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0013_remove_prescription_medicaments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='duree_traitement',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='nom_medicament',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='posologie',
        ),
        migrations.AddField(
            model_name='prescription',
            name='remarques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MedicamentPrescrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medicament', models.CharField(max_length=255)),
                ('posologie', models.TextField()),
                ('duree_traitement', models.PositiveIntegerField(help_text='Durée en jours')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='Doctor.prescription')),
            ],
        ),
    ]
