# Generated by Django 5.1.3 on 2025-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0014_remove_prescription_duree_traitement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='invite_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_mobile_linked',
            field=models.BooleanField(default=False),
        ),
    ]
