# Generated by Django 5.1.3 on 2025-08-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0016_rendezvous_medecin_rendezvous_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='created_at',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='alerte_medicale',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='domicile',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='etat_patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='invite_code',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='invite_expires_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_mobile_linked',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='personne_a_prevenir',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prenoms',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='situation_matrimoniale',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='tel_personne_prevenir',
        ),
        migrations.AddField(
            model_name='patient',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default=10, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='prenom',
            field=models.CharField(default='1234', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
