# Generated by Django 5.2.5 on 2025-08-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0017_rename_created_at_patient_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='personne_a_prevenir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='situation_matrimoniale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tel_personne_prevenir',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
