# Generated by Django 5.2.5 on 2025-08-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0018_patient_personne_a_prevenir_patient_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
